# docs https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

deployment:
  # DaemonSet ensures that there is only 1 pod per node
  kind: DaemonSet

# Specifying HostPort directly opens up the port on the Node itself
ports:
  web:
    port: 80
    hostPort: 80
  websecure:
    port: 443
    hostPort: 443
  metrics:
    port: 9100
    expose:
      default: true