kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-default-sa-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: "" # Empty namespace for cluster-wide access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring # Replace with your custom role name